export const postsUser = [
    {
      id: 1,
      author: "Никита Тик Ток",
      text: "Just finished an amazing photoshoot in the mountains! The golden hour lighting was absolutely perfect. Can't wait to share the results with you all! 📸✨",
      time: "2 hours ago",
      avatar: "https://avatars.githubusercontent.com/u/143941740?v=4",
      image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-KEkt9WNlawOqMoSiy5DAnjFlWoAH9H.png",
      likes: 42,
      comments: 8,
      shares: 3,
      commentsList: [
        {
          id: 1,
          author: "Анна",
          text: "Потрясающие фотографии! 😍",
          time: "1 hour ago",
          avatar: "/diverse-female-avatar.png",
          replies: [
            {
              id: 11,
              author: "Никита Тик Ток",
              text: "Спасибо большое! ❤️",
              time: "30 min ago",
              avatar: "https://avatars.githubusercontent.com/u/143941740?v=4",
            },
          ],
        },
        {
          id: 2,
          author: "Максим",
          text: "Золотой час действительно волшебный",
          time: "45 min ago",
          avatar: "/diverse-female-avatar.png",
          replies: [],
        },
      ],
    },
    {
      id: 2,
      author: "Никита Тик Ток",
      text: "Coffee and creativity go hand in hand. Starting my day with a fresh cup and some new ideas brewing! ☕️",
      time: "1 day ago",
      avatar: "https://avatars.githubusercontent.com/u/143941740?v=4",
      likes: 28,
      comments: 5,
      shares: 2,
      commentsList: [
        {
          id: 1,
          author: "Елена",
          text: "Кофе - это жизнь! ☕",
          time: "12 hours ago",
          avatar: "/diverse-female-avatar.png",
          replies: [],
        },
      ],
    },
    {
      id: 3,
      author: "Никита Тик Ток",
      text: "Grateful for all the support on my latest project. Your comments and shares mean the world to me! 🙏",
      time: "3 days ago",
      avatar: "https://avatars.githubusercontent.com/u/143941740?v=4",
      likes: 156,
      comments: 23,
      shares: 12,
      commentsList: [
        {
          id: 1,
          author: "Дмитрий",
          text: "Заслуженный успех! 👏",
          time: "2 days ago",
          avatar: "/diverse-female-avatar.png",
          replies: [],
        },
        {
          id: 2,
          author: "София",
          text: "Продолжай в том же духе!",
          time: "1 day ago",
          avatar: "/diverse-female-avatar.png",
          replies: [],
        },
      ],
    },
    {
      id: 4,
      author: "Никита Тик Ток",
      text: "Working on some exciting new features for the app. Can't wait to share what we've been building behind the scenes! 🚀",
      time: "5 days ago",
      avatar: "https://avatars.githubusercontent.com/u/143941740?v=4",
      likes: 89,
      comments: 15,
      shares: 7,
      commentsList: [
        {
          id: 1,
          author: "Алексей",
          text: "Интригующе! Жду обновления",
          time: "4 days ago",
          avatar: "/diverse-female-avatar.png",
          replies: [],
        },
      ],
    },
    {
      id: 5,
      author: "Никита Тик Ток",
      text: "Beautiful sunset from my balcony today. Sometimes you need to pause and appreciate the simple moments in life. 🌅",
      time: "1 week ago",
      avatar: "https://avatars.githubusercontent.com/u/143941740?v=4",
      likes: 203,
      comments: 31,
      shares: 18,
      commentsList: [
        {
          id: 1,
          author: "Мария",
          text: "Какая красота! 🌅",
          time: "6 days ago",
          avatar: "/diverse-female-avatar.png",
          replies: [],
        },
        {
          id: 2,
          author: "Игорь",
          text: "Согласен, важно ценить моменты",
          time: "5 days ago",
          avatar: "/diverse-female-avatar.png",
          replies: [],
        },
      ],
    },
  ]

export const userFriends = [
    { id: 1, name: "Bulat", avatar: "/diverse-female-avatar.png" },
    { id: 2, name: "Нина", avatar: "/diverse-female-avatar.png" },
    { id: 3, name: "Кафоленка", avatar: "/diverse-female-avatar.png" },
    { id: 4, name: "Валентина", avatar: "/diverse-female-avatar.png" },
    { id: 5, name: "Илья", avatar: "/diverse-female-avatar.png" },
    { id: 6, name: "Катерина", avatar: "/diverse-female-avatar.png" },
    { id: 7, name: "Даниил", avatar: "/diverse-female-avatar.png" },
    { id: 8, name: "Дмитрий", avatar: "/diverse-female-avatar.png" },
  ]